=== CeeJay79/AU-AD/AE-go_DataPack/gameserver/data/static_data/npc_teleporter.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="npc_teleporter">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="teleporter_template" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence />
						<xs:attribute name="npc_id" type="xs:int" use="required" />
						<xs:attribute name="name" type="xs:string" use="required" />
						<xs:attribute name="teleportId" type="xs:int" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== CeeJay79/AU-AD/AE-go_DataPack/gameserver/data/static_data/npc_teleporter.xml
<?xml version="1.0" encoding="UTF-8"?>
<npc_teleporter xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="npc_teleporter.xsd">
	<!-- Asmodians -->
	<!-- Pandaemonium -->
	<teleporter_template npc_id="204191" name="Doman" teleportId="50">
	</teleporter_template>
	<!-- Ishalgen -->
	<teleporter_template npc_id="203679" name="Osmar" teleportId="51">
	</teleporter_template>
	<!-- Altgard -->
	<teleporter_template npc_id="203581" name="Ukin" teleportId="52">
	</teleporter_template>
	<!-- Morheim -->
	<teleporter_template npc_id="204399" name="Orhe" teleportId="53">
	</teleporter_template>
	<!-- Brusthonin -->
	<teleporter_template npc_id="205124" name="Tusen" teleportId="54">
	</teleporter_template>
	<!-- Beluslan -->
	<teleporter_template npc_id="204724" name="Eda" teleportId="55">
	</teleporter_template>
	
	<!-- Elyos -->
	<!-- Poeta -->
	<teleporter_template npc_id="203194" name="Daines" teleportId="2">
	</teleporter_template>
	<teleporter_template npc_id="203070" name="Kustanon" teleportId="103">
	</teleporter_template>
	<!-- Sanctum -->
	<teleporter_template npc_id="203726" name="Polyidus" teleportId="1">
	</teleporter_template>
</npc_teleporter>
