=== CeeJay79/AU-AD/AE-go_GameServer/data/static_data/quests/quest.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="../global_types.xsd" />
	<xs:element name="quests" type="Quests" />
	
	<xs:complexType name="Quests">
		<xs:sequence>
			<xs:element name="quest" type="Quest" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="Quest">
		<xs:sequence>
			<xs:element name="conditions" type="Conditions" minOccurs="0" maxOccurs="1" />
			<xs:element name="quest_event" type="QuestEvent" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:int" use="required" />
		<xs:attribute name="start_npc_id" type="xs:int" />
		<xs:attribute name="end_npc_id" type="xs:int" />
	</xs:complexType>

	<xs:complexType name="Condition" abstract="true" >
		<xs:attribute name="op" type="ConditionOp" use="required" />
	</xs:complexType>

	<xs:complexType name="Conditions">
		<xs:sequence>
			<xs:element name="dialog_id" type="DialogIdCondition" minOccurs="0" maxOccurs="1" />
			<xs:element name="npc_id" type="NpcIdCondition" minOccurs="0" maxOccurs="1" />
			<xs:element name="pc_inventory" type="PcInventory" minOccurs="0" maxOccurs="1" />
			<xs:element name="pc_level" type="PcLevel" minOccurs="0" maxOccurs="1" />
			<xs:element name="quest_status" type="QuestStatusCondition" minOccurs="0" maxOccurs="1" />
			<xs:element name="quest_var" type="QuestVarCondition" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="operate" type="Operate" use="required" />
	</xs:complexType>
	
	<xs:complexType name="QuestEvent">
		<xs:sequence>
			<xs:element name="conditions" type="Conditions" minOccurs="0" maxOccurs="1" />
			<xs:element name="operations" type="Operations" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="type" type="EventType" use="required" />
		<xs:attribute name="ids" type="xs:token" />
	</xs:complexType>

	<xs:complexType name="Operations">
		<xs:sequence>
			<xs:element name="incrase_quest_var" type="IncraseQuestVarOperation" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="npc_dialog" type="NpcDialogOperation" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="set_quest_status" type="SetQuestStatusOperation" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="DialogIdCondition">
		<xs:complexContent>
			<xs:extension base="Condition">
				<xs:attribute name="value" type="xs:int" use="required" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="NpcIdCondition">
		<xs:complexContent>
			<xs:extension base="Condition">
				<xs:attribute name="values" type="xs:token" use="required" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="PcInventory">
		<xs:complexContent>
			<xs:extension base="Condition">
				<xs:attribute name="item_id" type="xs:int" use="required" />
				<xs:attribute name="count" type="xs:int" use="required" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="PcLevel">
		<xs:complexContent>
			<xs:extension base="Condition">
				<xs:attribute name="value" type="xs:int" use="required" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="PcRaceCondition">
		<xs:complexContent>
			<xs:extension base="Condition">
				<xs:attribute name="value" type="playerRace" use="required" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="QuestStatusCondition">
		<xs:complexContent>
			<xs:extension base="Condition">
				<xs:attribute name="value" type="QuestStatus" use="required" />
				<xs:attribute name="quest_id" type="xs:int" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="QuestVarCondition">
		<xs:complexContent>
			<xs:extension base="Condition">
				<xs:attribute name="value" type="xs:int" use="required" />
				<xs:attribute name="var_id" type="xs:int" use="required" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="GiveExpOperation">
		<xs:sequence/>
		<xs:attribute name="value" type="xs:int" use="required" />
	</xs:complexType>
	
	<xs:complexType name="GiveItemOperation">
		<xs:sequence/>
		<xs:attribute name="item_id" type="xs:int" use="required" />
		<xs:attribute name="count" type="xs:int" use="required" />
	</xs:complexType>
	
	<xs:complexType name="IncraseQuestVarOperation">
		<xs:sequence/>
		<xs:attribute name="var_id" type="xs:int" use="required" />
		<xs:attribute name="value" type="xs:int" use="required" />
	</xs:complexType>

	<xs:complexType name="NpcDialogOperation">
		<xs:sequence/>
		<xs:attribute name="id" type="xs:int" use="required" />
		<xs:attribute name="quest_id" type="xs:int" />
	</xs:complexType>
	
	<xs:complexType name="SetQuestStatusOperation">
		<xs:sequence/>
		<xs:attribute name="status" type="QuestStatus" use="required" />
	</xs:complexType>
	
	<xs:simpleType name="Operate">
		<xs:restriction base="xs:string">
			<xs:enumeration value="AND" />
			<xs:enumeration value="OR" />
		</xs:restriction>
	</xs:simpleType>
	
		<xs:simpleType name="ConditionOp">
		<xs:restriction base="xs:string">
			<xs:enumeration value="EQUAL" />
			<xs:enumeration value="GREATER" />
			<xs:enumeration value="GREATER_EQUAL" />
			<xs:enumeration value="LESSER" />
			<xs:enumeration value="LESSER_EQUAL" />
			<xs:enumeration value="NOT_EQUAL" />
			<xs:enumeration value="IN" />
			<xs:enumeration value="NOT_IN" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="QuestStatus">
		<xs:restriction base="xs:string">
			<xs:enumeration value="NONE" />
			<xs:enumeration value="START" />
			<xs:enumeration value="REWARD" />
			<xs:enumeration value="COMPLITE" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="EventType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ON_TALK" />
			<xs:enumeration value="ON_KILL" />
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== CeeJay79/AU-AD/AE-go_GameServer/data/static_data/quests/quest.xml
<?xml version="1.0" encoding="UTF-8"?>
<quests xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="quest.xsd">

	<quest id="1000" start_npc_id="0" end_npc_id="0"/>
	<quest id="2000" start_npc_id="0" end_npc_id="0"/>

	<quest id="1101" start_npc_id="203049" end_npc_id="203057"/>

	<quest id="1102" start_npc_id="203057" end_npc_id="203057">

		<quest_event type="on_kill" ids="210133, 210134, 210705">
			<condition operate="AND">
				<quest_var op="LESSER" var_id="0" value="3" />
			</condition>
			<operations>
				<incrase_quest_var var_id="0" value="1" />
			</operations>
		</quest_event>

		<quest_event type="on_talk" ids="203057">
			<condition operate="AND">
				<dialog_id op="EQUAL" value="25" />
				<quest_status op="EQUAL" value="START" />
			</condition>
			<operations>
				<npc_dialog id="1352" />
			</operations>
		</quest_event>
	</quest>

	<quest id="1103" start_npc_id="203057" end_npc_id="203057"/>

	<quest id="1104" start_npc_id="203057" end_npc_id="203059"/>

	<quest id="1105" start_npc_id="203050" end_npc_id = "203050" />

	<quest id="1106" start_npc_id="203050" end_npc_id = "203061" />

	<quest id="1108" start_npc_id="203061" end_npc_id = "203061" />

	<quest id="1109" start_npc_id="798007" end_npc_id = "798007" />

	<quest id="1110" start_npc_id="203065" end_npc_id = "730008" />

	<quest id="1111" start_npc_id="203075" end_npc_id = "203075" />

	<quest id="1112" start_npc_id="203072" end_npc_id="203072">
		<quest_event type="on_kill" ids="210259, 210260, 210672">
			<condition operate="AND">
				<quest_var op="LESSER" var_id="0" value="5" />
			</condition>
			<operations>
				<incrase_quest_var var_id="0" value="1" />
			</operations>
		</quest_event>

		<quest_event type="on_kill" ids="210065, 210066">
			<condition operate="AND">
				<quest_var op="LESSER" var_id="1" value="5" />
			</condition>
			<operations>
				<incrase_quest_var var_id="1" value="1" />
			</operations>
		</quest_event>

		<quest_event type="on_talk" ids="203072">
			<condition operate="AND">
				<dialog_id op="EQUAL" value="25" />
				<quest_var op="GREATER_EQUAL" var_id="0" value="5" />
				<quest_var op="GREATER_EQUAL" var_id="1" value="5" />
				<quest_status op="EQUAL" value="START" />
			</condition>
			<operations>
				<npc_dialog id="1352" />
			</operations>
		</quest_event>
	</quest>
</quests>
