=== CeeJay79/AU-AD/AE-go_GameServer/data/static_data/cube_expander/cube_expander.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="../import.xsd" />
	<xs:element name="cube_expander">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="import" minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="cube_npc" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence />
						<xs:attribute name="id" type="xs:int" use="required" />
						<xs:attribute name="name" type="xs:string" use="required" />
						<xs:attribute name="min_level" type="xs:int" use="required" />
						<xs:attribute name="max_level" type="xs:int" use="required"/>
						<xs:attribute name="price01" type="xs:int" />
						<xs:attribute name="price02" type="xs:int" />
						<xs:attribute name="price03" type="xs:int" />
						<xs:attribute name="price04" type="xs:int" />
						<xs:attribute name="price05" type="xs:int" />
						<xs:attribute name="price06" type="xs:int" />
						<xs:attribute name="price07" type="xs:int" />
						<xs:attribute name="price08" type="xs:int" />
						<xs:attribute name="price09" type="xs:int" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== CeeJay79/AU-AD/AE-go_GameServer/data/static_data/cube_expander/cube_expander.xml
<?xml version="1.0" encoding="UTF-8"?>
<cube_expander xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cube_expander.xsd">

	<!-- Instructions 
		min_level and max_level reflects current cube expansion level. By default it is 0 (not yet expanded)
		price01 - is the price to expand to level 1 from level 0
		..
		price09 - is the price to expand to level 9 from level 8
		
		The difference (max_level - min_level + 1) should be equal to number of prices specified
	-->
	
	<!-- Poeta -->
	<cube_npc id="798008" name="Baevrunerk" min_level="0" max_level="0" price01="1000" />
	<!-- Ishalgen -->
	<cube_npc id="798037" name="Bacorerk" min_level="0" max_level="0" price01="1000" />
	<!-- Pandaemonium -->
	<cube_npc id="798058" name="Ondarinerk" min_level="1" max_level="3" price02="12000" price03="80000" price04="180000" />
	<cube_npc id="798059" name="Nekorunerk" min_level="1" max_level="3" price02="12000" price03="80000" price04="180000" />
	<!-- Sanctum -->
	<cube_npc id="798011" name="Heerunerk" min_level="1" max_level="3" price02="12000" price03="80000" price04="180000" />
	<cube_npc id="798012" name="Yiehmonerk" min_level="1" max_level="3" price02="12000" price03="80000" price04="180000" />
	<!-- Abyss, Tigraki Island -->
	<cube_npc id="279022" name="Jarumonerk" min_level="3" max_level="3" price04="356103" />
</cube_expander>
